CREATE TABLE IF NOT EXISTS hero (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(32) NOT NULL,
    level INT NOT NULL,
    hp DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS artefact (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    type VARCHAR(32) NOT NULL,
    value DOUBLE NOT NULL,
    hero_id INT,
    FOREIGN KEY (hero_id) REFERENCES hero(id)
);
